// <auto-generated />
namespace nhóm6_BTL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ceate_table_hanghoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ceate_table_hanghoa));
        
        string IMigrationMetadata.Id
        {
            get { return "202111050724272_ceate_table_hanghoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
